version: "2"
services:
  app:
    build: .
    user: $UID:$GID
    volumes:
    - ./artifacts:/usr/src/app/artifacts
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"